spring.application.name=Battle.ioAPI

# PostgreSQL datasource - reemplaza Usuario/contraseña/host/puerto si es necesario
spring.datasource.url=jdbc:postgresql://localhost:5432/BattleIO
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.docker.compose.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.port=8080